#!/usr/bin/env bash

usage() {
    echo "ERROR: $0 <VERSION>"
    exit 1
}

VERSION=$1

[ -z "${VERSION}" ] && usage

STAGE_KEY="MEMutJjWBF0qNOqd6pqTuDPvL07ZbHT1"
PROD_KEY="jLwurYoMosZliChljnSNq7mCAOOd8Vnn"

case ${VERSION} in
    # Account for dev builds with 0.0.0 versioning
    0.0.0*|*dev*|*tp*|*beta*)
        echo "${STAGE_KEY}"
        ;;
    *)
        echo "${PROD_KEY}"
        ;;
esac
